### ISSUE TITLE
Dependency's

### ISSUE THREAD

**Issue by andrewsalmon** [nsuchy/nginx-naxsi-installer#2]
Using your script the first time failed me. But this is okay.

First issue: nginx masked. (Confused me but easily fixed "systemctl unnmask nginx")

Second issue: Nginx wasn't installed. (Whaa? )

So I decided to try to run your script manually. (Enter the commands line by line myself)

When trying to compile nginx:
"error: the HTTP rewrite module requires the PCRE library."
"error: SSL modules require the OpenSSL library."

So, I installed the libraries and it worked fine. ("apt-get install libpcre3 libpcre3-dev libssl-dev

The only other thing was a warning
"./configure: warning: the "--with-ipv6" option is deprecated"

So: Why is this an issue? You have installed *most* dependacy's with your script but not all. And I simply wanted to point out that you need to include those as well.

Suggestion: Consider the users that already had nginx installed (e.g. uninstall nginx and whatnot, maybe rm the old directory and such so we don't have to do it manually)

But thank you for making this script so easy to use and all. I absolutely love your GitHub page and all it's content.

**Comment by andrewsalmon** [comment]
One more comment: You use /usr/local/nginx in this ("include /usr/local/nginx/conf/naxsi_core.rules;") but on my server it is /etc/nginx instead where everything is located and I'd prefer for everything to be in one spot vs multiple.  
So if you could take that into consideration as well ^

**Comment by nsuchy** [comment]
Did you run the script on a clean install of Ubuntu? You said something about the /etc/nginx directory in the email. This script configures everything to use the /usr/local/nginx/ directory so it's all in one place. The script uses nginx's build-dep from apt so maybe it overlooked some dependencies (I can add "apt-get install libpcre3 libpcre3-dev libssl-dev" to the script as mandatory and see if that resolves the issue.). Thoughts?

**Comment by andrewsalmon** [comment]
It isn't a clean install.

And yeah, I deleted that comment. I'm used to the nginx directory being /etc/nginx not /usr/local/nginx so I was a bit confused at first, but once I commented I realized what was going on and deleted it.

And makes sense. 
I installed nginx and such now, it's all working. I just wanted to point out that for me, this was an issue and for someone else it could be too.

Adding those to the install list in the script is what I was thinking, so yes that would workout just fine.

**Comment by andrewsalmon** [comment]
One problem I'm having right now:
The nginx config is in /usr/local/nginx/conf/nginx.conf , as configure by your script.

The init.d script you have is pointing towards /usr/local/nginx/nginx.conf instead and making me unable to start nginx.
(Easily fixable. But again, I'm just trying to point this out)

**Comment by nsuchy** [comment]
@andrewsalmon You said it's a simple fix - would you mind writing out detailed instructions on how you'd like the configuration adjusted?

**Comment by andrewsalmon** [comment]
First issue: Just add "apt-get install libpcre3 libpcre3-dev libssl-dev" to your setup.sh script (Otherwise it does not install nginx correctly)

Second thing: Just change line 31 of nginx-initd.sh from "/usr/local/nginx/nginx.conf" to "/usr/local/nginx/conf/nginx.conf"  (Otherwise I cannot start nginx correctly)

**Comment by nsuchy** [comment]
Thank you for your feedback - I'm working upon the requested changes and will try to get it done in a timely manner.

**Comment by andrewsalmon** [comment]
Thank you, very much. 
You have a nice script and I just would like to see it work properly.

**Comment by nsuchy** [comment]
It works on many Ubuntu distros based on 16.04 LTS however I overlooked that some hosts may use their own APT Repos so the build-dep doesn't have all the required sources. The goal of the script is to require zero human interaction (it should be perfect for applying to 1 or 10,000 servers - you should be able to adjust the script for your need (such as mass deploying your nginx configs) for massive automation.

**Comment by nsuchy** [comment]
The issue should be resolved now, please see: https://github.com/nsuchy/nginx-naxsi-installer/commit/a4f3ac3b667bb9415ab6f3eda12ec20eec215038 and let me know if you have further comment or if the issue can be closed.

**Comment by andrewsalmon** [comment]
That's all. Thank you!
